"""Initial

Revision ID: 029882430866
Revises:
Create Date: 2024-04-30 12:37:06.394272+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029882430866'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.Column('shortcut_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_values',
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('value_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], ),
    sa.PrimaryKeyConstraint('value_id')
    )
    op.create_table('story_labels',
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], )
    )
    op.create_table('story_custom_fields',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('custom_field_value_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_value_id'], ['custom_field_values.value_id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'custom_field_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_custom_fields')
    op.drop_table('story_labels')
    op.drop_table('custom_field_values')
    op.drop_table('stories')
    op.drop_table('labels')
    op.drop_table('custom_fields')
    # ### end Alembic commands ###
