"""Add story status

Revision ID: 887b3cbc657d
Revises: 029882430866
Create Date: 2024-05-10 14:46:41.662916+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '887b3cbc657d'
down_revision: Union[str, None] = '029882430866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('active', sa.Boolean(), nullable=False,
                                       default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'active')
    # ### end Alembic commands ###
