"""Add story epic groups

Revision ID: ad590e37d53e
Revises: 9addf8ff2958
Create Date: 2024-05-29 10:32:03.274692+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad590e37d53e'
down_revision: Union[str, None] = '9addf8ff2958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epic_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_epic_groups',
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('epic_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['epic_group_id'], ['epic_groups.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_epic_groups')
    op.drop_table('epic_groups')
    # ### end Alembic commands ###
